[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = {version = "1.5.0", features = ["spin_no_std"]}
pic8259 = "0.11.0"
spin = "0.9.8"
uart_16550 = "0.3.1"
x86_64 = "0.15.1"
